#______________[português]____________________
# Copyright (c) 2026 John-BrenoF
# Este programa é um software livre: você pode redistribuí-lo e/ou modificá-lo
# sob os termos da licença LUMEJ v1.0. Veja o arquivo LICENSE no repositório.
#_____________[english]____________________
# Copyright (c) 2016-2026 John-BrenoF
# This program is free software: you can redistribute it and/or modify it
# under the terms of the LUMEJ v1.0 license. See the LICENSE file in the repository.

from typing import Protocol, Callable, Optional, Tuple, Any
from dataclasses import dataclass

@dataclass
class EditorEvent:
    char: str
    keysym: str
    modifiers: int = 0

class EditHistoryController(Protocol):
    def on_content_loaded(self, content: str, baseline: Optional[str] = None, force_dirty: bool = False) -> None: ...
    def mark_saved(self, content: str) -> None: ...
    def on_text_input(self, char: Optional[str]) -> None: ...
    def perform_undo(self) -> None: ...
    def perform_redo(self) -> None: ...
    def begin_transaction(self) -> None: ...
    def end_transaction(self) -> None: ...
    @property
    def is_dirty(self) -> bool: ...

class TextEditor(Protocol):
    def insert(self, text: str, index: str = "insert") -> None: ...
    def delete(self, start: str, end: Optional[str] = None) -> None: ...
    def set_text(self, text: str) -> None: ...
    def get_text(self, start: str = "1.0", end: str = "end") -> str: ...
    def get_cursor_index(self) -> str: ...
    def set_cursor(self, index: str) -> None: ...
    def get_selection_range(self) -> Optional[Tuple[str, str]]: ...
    def bind_key(self, key: str, callback: Callable[[EditorEvent], Any]) -> None: ...
    def index_offset(self, index: str, chars: int) -> str: ...
    def get_char_at(self, index: str) -> str: ...
    def get_line_count(self) -> int: ...
    def apply_tag(self, tag_name: str, start: str, end: str) -> None: ...
    def configure_tag(self, tag_name: str, **kwargs) -> None: ...
    def get_tags(self) -> Tuple[str, ...]: ...
    def delete_tag(self, tag_name: str) -> None: ...
    def remove_tag(self, tag_name: str, start: str, end: str) -> None: ...
    # Melhorias para Undo/Redo
    def undo(self) -> None: ...
    def redo(self) -> None: ...
    def edit_separator(self) -> None: ...
    def reset_undo_stack(self) -> None: ...
    # Novos métodos para controle atômico
    def begin_undo_group(self) -> None: ...
    def end_undo_group(self) -> None: ...
    def is_in_transaction(self) -> bool: ...

class StatusBar(Protocol):
    def update_status(self, line: int, column: int, file_path: str) -> None: ...
    def update_git_ui(self, status_text: str, is_dirty: bool) -> None: ...

class Sidebar(Protocol):
    def refresh_explorer(self) -> None: ...
    @property
    def item_widgets(self) -> dict: ...

class AppWindow(Protocol):
    def after(self, ms: int, func: Callable) -> None: ...
    def destroy(self) -> None: ...
    def bind(self, sequence: str, func: Callable) -> None: ...

class ThemeProvider(Protocol):
    def get(self, section: str, default: Any = None) -> Any: ...