from ui.sidebar import Sidebar
from core.src.app_context import AppContext

Sidebar.register_plugin_icons(
    new_icons={
  ".py": " ",
  ".md": "󰍔 ",
  ".json": " ",
  ".txt": "󰈙 ",
  ".sh": "󱆃 ",
  ".gitignore": "󰊢 ",
  ".session_config": "󰒓 ",
  ".html": " ",
  ".css": "󰝉 ",
  ".js": "󰝎 ",
  ".ts": "󰛦 ",
  ".tsx": "󰜈 ",
  ".jsx": "󰜏 ",
  ".rs": "󱘊 ",
  ".go": "󰟓 ",
  ".cpp": "󰙲 ",
  ".c": "󰙱 ",
  ".h": "󰙰 ",
  ".hpp": "󰙰 ",
  ".java": "󰬷 ",
  ".kt": "󱈙 ",
  ".rb": "󰴭 ",
  ".php": "󰌽 ",
  ".sql": "󰆆 ",
  ".db": "󰆓 ",
  ".sqlite": "󰆓 ",
  ".yml": "󰅴 ",
  ".yaml": "󰅴 ",
  ".toml": "󰅪 ",
  ".xml": "󰜮 ",
  ".svg": "󰜡 ",
  ".png": "󰋩 ",
  ".jpg": "󰋩 ",
  ".jpeg": "󰋩 ",
  ".gif": "󰋩 ",
  ".ico": "󰋩 ",
  ".mp3": "󰝚 ",
  ".wav": "󰝚 ",
  ".flac": "󰝚 ",
  ".mp4": "󰕧 ",
  ".mkv": "󰕧 ",
  ".avi": "󰕧 ",
  ".zip": "󰛫 ",
  ".tar": "󰛫 ",
  ".gz": "󰛫 ",
  ".rar": "󰛫 ",
  ".7z": "󰛫 ",
  ".pdf": "󰈦 ",
  ".doc": "󰈬 ",
  ".docx": "󰈬 ",
  ".xls": "󰈛 ",
  ".xlsx": "󰈛 ",
  ".ppt": "󰈧 ",
  ".pptx": "󰈧 ",
  ".dockerfile": "󰡨 ",
  "dockerfile": "󰡨 ",
  ".env": "󰒓 ",
  ".log": "󰌱 ",
  ".lock": "󰌾 ",
  ".vue": "󰡄 ",
  ".svelte": "󰟤 ",
  ".astro": "󱓞 ",
  ".lua": "󰢱 ",
  ".scala": "󰌆 ",
  ".clj": "󰡱 ",
  ".hs": "󰲒 ",
  ".ex": "󰎡 ",
  ".exs": "󰎡 ",
  ".elm": "󰟆 ",
  ".dart": "󰎙 ",
  ".swift": "󰛥 ",
  ".r": "󰟔 ",
  ".jl": "󰰅 ",
  ".nim": "󰆥 ",
  ".zig": "󰱺 ",
  ".sol": "󰡯 ",
  ".tf": "󱁢 ",
  ".unity": "󰚯 ",
  ".godot": "󰑣 ",
  ".bzl": "󰊭 ",
  ".cmake": "󰅨 ",
  ".makefile": "󰏔 ",
  "makefile": "󰏔 ",
  "gemfile": "󰴭 ",
  "rakefile": "󰴭 ",
  "package.json": "󰎙 ",
  "tsconfig.json": "󰛦 "
}
)

ctx = AppContext()
if hasattr(ctx, 'sidebar') and ctx.sidebar:
    ctx.sidebar.refresh_explorer()